services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    env_file:
      - .env
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kathmandu
      - WEBUI_PORT=8880
      - TORRENTING_PORT=6881
    volumes:
      - $HOMELAB_DATA_DIR/qbittorrent_data/appdata/config:/config
      - /home/rahul/Downloads/qbittorrent:/downloads
      - ./webhooks:/webhooks
    dns:
      - 8.8.8.8
      - 4.4.4.4
    ports:
      - 8880:8880
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
    networks:
      - media-server

networks:
  media-server:
    external: true

