version: '3.5'
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: ""
    network_mode: 'host'
    volumes:
      - jellyfin-config:/config
      - jellyfin-cache:/cache
      - type: bind
        source: /jellyfin
        target: /media
      - $HOME/Downloads/qbittorrent:/downloads

    restart: 'unless-stopped'
    extra_hosts:
      - 'host.docker.internal:host-gateway'

volumes:
  jellyfin-config:
  jellyfin-cache:

